sudo: false
language: node_js
node_js:
  - "14"
  - "13"
  - "12"
  - "10"
matrix:
  allow_failures:
    - node_js: "13"

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
